### ISSUE TITLE
subproject names are confusing

### ISSUE THREAD

**Issue by walterxie** [bioDS/beast-phylonco#20]
Hi @kche309 and @J-Moravec,

After Alexei reviewed the develop tutorial, he advised the subproject names were very confusing, which might imply the subfolders containing all of cores (e.g. lphy, beast2). I think they are confusing. I will change these 3 subfolders (sub-projects) into: `phylonco-b2`, `phylonco-lphy`, and `phylonco-lb`. Previously these names were defined by base names. In this change, I will remove the base names, so Gradle can use the subproject names for naming as the default.

Do you want me to create a branch for this change?

**Comment by kche309** [comment]
Hi @walterxie 
I have also noticed this issue, especially if you are developing code it is easy to confuse it for beast2 core. 

I would suggest renaming directories and jars to `phylonco-beast`, `phylonco-lphy` and `phylonco-lphybeast`.

Please create a branch for changes, and use `git mv` to do the renaming.

**Comment by J-Moravec** [comment]
Agree with Kylie, `phylonco-beast` etc. is better, there is no reason to be less expressive.

**Comment by walterxie** [comment]
Everything looks OK.
